/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as PosterIndexImport } from './routes/poster/index'
import { Route as BusinessProfileIndexImport } from './routes/business-profile/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PosterIndexRoute = PosterIndexImport.update({
  id: '/poster/',
  path: '/poster/',
  getParentRoute: () => rootRoute,
} as any)

const BusinessProfileIndexRoute = BusinessProfileIndexImport.update({
  id: '/business-profile/',
  path: '/business-profile/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/business-profile/': {
      id: '/business-profile/'
      path: '/business-profile'
      fullPath: '/business-profile'
      preLoaderRoute: typeof BusinessProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/poster/': {
      id: '/poster/'
      path: '/poster'
      fullPath: '/poster'
      preLoaderRoute: typeof PosterIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/business-profile': typeof BusinessProfileIndexRoute
  '/poster': typeof PosterIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/business-profile': typeof BusinessProfileIndexRoute
  '/poster': typeof PosterIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRoute
  '/business-profile/': typeof BusinessProfileIndexRoute
  '/poster/': typeof PosterIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/business-profile' | '/poster'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/business-profile' | '/poster'
  id: '__root__' | '/' | '/_layout' | '/business-profile/' | '/poster/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRoute
  BusinessProfileIndexRoute: typeof BusinessProfileIndexRoute
  PosterIndexRoute: typeof PosterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRoute,
  BusinessProfileIndexRoute: BusinessProfileIndexRoute,
  PosterIndexRoute: PosterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/business-profile/",
        "/poster/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx"
    },
    "/business-profile/": {
      "filePath": "business-profile/index.tsx"
    },
    "/poster/": {
      "filePath": "poster/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
