/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QrResultsPageImport } from './routes/QrResultsPage'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const QrResultsPageLazyImport = createFileRoute('/qr-results-page')()

// Create/Update Routes

const QrResultsPageLazyRoute = QrResultsPageLazyImport.update({
  id: '/qr-results-page',
  path: '/qr-results-page',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/qr-results-page.lazy').then((d) => d.Route),
)

const QrResultsPageRoute = QrResultsPageImport.update({
  id: '/QrResultsPage',
  path: '/QrResultsPage',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/QrResultsPage': {
      id: '/QrResultsPage'
      path: '/QrResultsPage'
      fullPath: '/QrResultsPage'
      preLoaderRoute: typeof QrResultsPageImport
      parentRoute: typeof rootRoute
    }
    '/qr-results-page': {
      id: '/qr-results-page'
      path: '/qr-results-page'
      fullPath: '/qr-results-page'
      preLoaderRoute: typeof QrResultsPageLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/QrResultsPage': typeof QrResultsPageRoute
  '/qr-results-page': typeof QrResultsPageLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/QrResultsPage': typeof QrResultsPageRoute
  '/qr-results-page': typeof QrResultsPageLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/QrResultsPage': typeof QrResultsPageRoute
  '/qr-results-page': typeof QrResultsPageLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/QrResultsPage' | '/qr-results-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/QrResultsPage' | '/qr-results-page'
  id: '__root__' | '/' | '/QrResultsPage' | '/qr-results-page'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QrResultsPageRoute: typeof QrResultsPageRoute
  QrResultsPageLazyRoute: typeof QrResultsPageLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QrResultsPageRoute: QrResultsPageRoute,
  QrResultsPageLazyRoute: QrResultsPageLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/QrResultsPage",
        "/qr-results-page"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/QrResultsPage": {
      "filePath": "QrResultsPage.tsx"
    },
    "/qr-results-page": {
      "filePath": "qr-results-page.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
